name: grupo-1-frontend
services:
  frontend:
    image: cleviobecerra/grupo-1-frontend:entrega-9
    ports:
      - "80:80"
  plantopia:
    image: cnicolas86/plantopia:1.2.0
    container_name: plantopia-prod
    ports:
      - "4000:4000"
    env_file:
      - ./.env.productivo # Carga las variables de entorno desde el archivo .env.productivo
    depends_on:
      - mysql  # Asegúrate de que MySQL esté listo antes de levantar la app
    networks:
      - plantopia-network

  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PlantopiaDB
      MYSQL_USER: user_prod
      MYSQL_PASSWORD: password_prod
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - plantopia-network

networks:
  plantopia-network:
    driver: bridge